# Generated by Django 5.1 on 2024-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('click', 'Click'), ('payme', 'Payme')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=20, null=True, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='created', max_length=20, verbose_name='Status'),
        ),
    ]
